SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

-- SQL Server 2022 schema (FREE v8.1)
CREATE TABLE Instruments(
  InstrumentId INT IDENTITY PRIMARY KEY,
  Symbol NVARCHAR(32) NOT NULL UNIQUE,
  AssetClass NVARCHAR(16) CHECK (AssetClass IN ('CRYPTO','EQ','ETF','FX','CMDT')) NOT NULL,
  Venue NVARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
  PointValue DECIMAL(18,8) NOT NULL DEFAULT 1.0,
  TickSize DECIMAL(18,8) NOT NULL DEFAULT 0.0001,
  Currency CHAR(3) NOT NULL DEFAULT 'USD',
  LotSize DECIMAL(18,8) NOT NULL DEFAULT 1.0,
  IsActive BIT NOT NULL DEFAULT 1,
  Tags NVARCHAR(128) NULL,
  CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2(3) NULL
);

CREATE TABLE Trades(
  TradeId BIGINT IDENTITY PRIMARY KEY,
  CorrelationId UNIQUEIDENTIFIER NOT NULL,
  ExternalRef NVARCHAR(64) NULL,
  InstrumentId INT NOT NULL,
  Strategy NVARCHAR(32) NOT NULL,
  Side CHAR(1) CHECK (Side IN ('B','S')) NOT NULL,
  Qty DECIMAL(18,8) NOT NULL,
  Entry DECIMAL(18,8) NOT NULL,
  Stop DECIMAL(18,8) NOT NULL,
  Target DECIMAL(18,8) NULL,
  EntryType NVARCHAR(16) NOT NULL DEFAULT 'STOP',
  OpenedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  ClosedAt DATETIME2(3) NULL,
  ExitPrice DECIMAL(18,8) NULL,
  ExitReason NVARCHAR(32) NULL,
  Status NVARCHAR(16) CHECK (Status IN ('PENDING','OPEN','CLOSED','CANCELLED','REJECTED')) NOT NULL DEFAULT 'PENDING',
  RiskPct DECIMAL(8,6) NOT NULL DEFAULT 0.003500,
  RealizedPnl DECIMAL(18,8) NULL,
  RealizedR DECIMAL(10,4) NULL,
  MaxAdverseExcursion DECIMAL(18,8) NULL,
  MaxFavorableExcursion DECIMAL(18,8) NULL,
  Tags NVARCHAR(128) NULL,
  Notes NVARCHAR(512) NULL,
  CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2(3) NULL,
  CONSTRAINT FK_Trades_Instrument FOREIGN KEY(InstrumentId) REFERENCES Instruments(InstrumentId)
);

CREATE TABLE Executions(
  ExecId BIGINT IDENTITY PRIMARY KEY,
  TradeId BIGINT NOT NULL,
  OrderId UNIQUEIDENTIFIER NULL,
  Ts DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  Source NVARCHAR(32) NULL,
  Venue NVARCHAR(32) NULL,
  FillType NVARCHAR(16) NOT NULL DEFAULT 'FILL',
  Price DECIMAL(18,8) NOT NULL,
  Qty DECIMAL(18,8) NOT NULL,
  Fee DECIMAL(18,8) NULL,
  FeeCurrency CHAR(3) NULL,
  Status NVARCHAR(16) NOT NULL,
  Liquidity NVARCHAR(8) NULL,
  Metadata NVARCHAR(MAX) NULL,
  CONSTRAINT FK_Exec_Trade FOREIGN KEY(TradeId) REFERENCES Trades(TradeId)
);

CREATE TABLE Signals(
  SignalId BIGINT IDENTITY PRIMARY KEY,
  Ts DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  InstrumentId INT NOT NULL,
  Strategy NVARCHAR(32) NOT NULL,
  Side CHAR(1) CHECK (Side IN ('B','S')) NOT NULL,
  Score DECIMAL(18,6) NOT NULL,
  RiskFraction DECIMAL(8,6) NOT NULL DEFAULT 0.003500,
  Entry DECIMAL(18,8) NULL,
  Stop DECIMAL(18,8) NULL,
  Target DECIMAL(18,8) NULL,
  ExpiryTs DATETIME2(3) NULL,
  Features NVARCHAR(MAX) NULL,
  Recommended NVARCHAR(MAX) NULL,
  Metadata NVARCHAR(MAX) NULL,
  CONSTRAINT FK_Signals_Instrument FOREIGN KEY(InstrumentId) REFERENCES Instruments(InstrumentId)
);

CREATE TABLE RiskEvents(
  EventId BIGINT IDENTITY PRIMARY KEY,
  Ts DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  Type NVARCHAR(32) NOT NULL,
  Severity NVARCHAR(16) NOT NULL DEFAULT 'INFO',
  InstrumentId INT NULL,
  TradeId BIGINT NULL,
  CorrelationId UNIQUEIDENTIFIER NULL,
  Detail NVARCHAR(MAX) NULL,
  Data NVARCHAR(MAX) NULL,
  CONSTRAINT FK_RiskEvents_Instrument FOREIGN KEY(InstrumentId) REFERENCES Instruments(InstrumentId),
  CONSTRAINT FK_RiskEvents_Trade FOREIGN KEY(TradeId) REFERENCES Trades(TradeId)
);

CREATE TABLE RiskLimits(
  LimitId INT IDENTITY PRIMARY KEY,
  Mode NVARCHAR(16) NOT NULL,
  DailyStopPct DECIMAL(7,4) NOT NULL,
  WeeklyStopPct DECIMAL(7,4) NOT NULL,
  PerTradePct DECIMAL(7,4) NOT NULL,
  MaxPositions INT NOT NULL DEFAULT 3,
  MaxGrossExposure DECIMAL(18,2) NULL,
  CoolingMinutes INT NOT NULL DEFAULT 0,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2(3) NULL
);

CREATE TABLE AuditLogs(
  AuditId BIGINT IDENTITY PRIMARY KEY,
  Ts DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  Component NVARCHAR(64) NOT NULL,
  Level NVARCHAR(16) NOT NULL,
  Message NVARCHAR(256) NOT NULL,
  Detail NVARCHAR(MAX) NULL,
  CorrelationId UNIQUEIDENTIFIER NULL,
  TradeId BIGINT NULL,
  InstrumentId INT NULL,
  Metadata NVARCHAR(MAX) NULL,
  CONSTRAINT FK_AuditLogs_Trade FOREIGN KEY(TradeId) REFERENCES Trades(TradeId),
  CONSTRAINT FK_AuditLogs_Instrument FOREIGN KEY(InstrumentId) REFERENCES Instruments(InstrumentId)
);

CREATE TABLE PortfolioSnapshots(
  SnapshotId BIGINT IDENTITY PRIMARY KEY,
  Ts DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  Equity DECIMAL(18,2) NOT NULL,
  Cash DECIMAL(18,2) NOT NULL,
  UnrealizedPnl DECIMAL(18,2) NOT NULL,
  RealizedPnl DECIMAL(18,2) NOT NULL,
  GrossExposure DECIMAL(18,2) NULL,
  NetExposure DECIMAL(18,2) NULL,
  Positions NVARCHAR(MAX) NULL
);

CREATE INDEX IX_Instruments_Symbol ON Instruments(Symbol);
CREATE INDEX IX_Trades_Status ON Trades(Status, OpenedAt DESC);
CREATE INDEX IX_Trades_Instrument ON Trades(InstrumentId, OpenedAt DESC);
CREATE INDEX IX_Executions_Trade ON Executions(TradeId, Ts DESC);
CREATE INDEX IX_Signals_Instrument_Ts ON Signals(InstrumentId, Ts DESC);
CREATE INDEX IX_RiskEvents_Ts ON RiskEvents(Ts DESC);
CREATE INDEX IX_RiskEvents_Type ON RiskEvents(Type, Severity);
CREATE UNIQUE INDEX IX_RiskLimits_Mode ON RiskLimits(Mode) WHERE IsActive = 1;
CREATE INDEX IX_AuditLogs_Ts ON AuditLogs(Ts DESC);
